# 站点基本信息
title: Milanfx 的个人主页
author:
  name: milanfx
  email: your-email@example.com
description: >
  这里是 Milanfx 的个人主页，分享数据科学、机器学习和生活点滴。

# 使用 minima 主题
theme: minima

# 使用必要插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima 主题的自定义
minima:
  skin: classic   # 经典明亮皮肤
  nav_pages:
    - about.md    # about 页链接到导航
  show_excerpts: false  # 首页是否显示文章摘录（false 则不显示）

# 如果有社交媒体链接，可添加到下面
# minima:
#   social_links:
#     - title: GitHub
#       icon: github
#       url: "https://github.com/milanfx"

